import type { Metadata } from 'next';
import { Quicksand } from 'next/font/google';
import './globals.css';
import clsx from 'clsx';

const quickSand = Quicksand({
  variable: '--font-quicksand',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  style: 'normal',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={(clsx(quickSand.variable), 'antialiased ')}>
        {children}
      </body>
    </html>
  );
}
